import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Info } from 'lucide-react'
import Link from 'next/link'
import React from 'react'

export default function AboutPage() {
  return (
    <div className="container mx-auto max-w-2xl p-4">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Info className="text-primary" />
            About Sunrise Flow
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p>
            Sunrise Flow is your all-in-one companion to start your day with
            intention and peace. We believe that a great day starts with a
            great morning.
          </p>
          <p>
            Our mission is to combine the essential tools you need—a smart alarm,
            a task planner, and guided meditations—into one beautiful and
            intuitive application.
          </p>
          <h3 className="font-semibold text-lg">Our Features:</h3>
          <ul className="list-disc list-inside space-y-2">
            <li>
              <strong>Smart Alarms:</strong> Wake up gently with customizable
              sounds and puzzles to get your brain working.
            </li>
            <li>
              <strong>Daily Planner:</strong> Organize your day with a simple and
              effective to-do list with priorities.
            </li>
            <li>
              <strong>Guided Meditation:</strong> Find your center with personalized
              meditation playlists generated by AI.
            </li>
          </ul>
          <p>
            This app was built with Next.js, Tailwind CSS, and Firebase.
          </p>
          <div className="pt-4">
             <Link href="/settings" className="text-primary hover:underline">
                &larr; Back to Settings
             </Link>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
